### ISSUE TITLE
Update backgrounds.json with 2 resolutions: 1920x1080 and 1920x1200

### ISSUE THREAD

**Issue by anticafe** [dconnolly/chromecast-backgrounds#6]
I notice [this website](http://chromecastbg.alexmeub.com/downloads.html) allow us to download all Chromecast backgrounds with 2 resolutions: 1920x1080 and 1920x1200.

Your `backgrounds.json` is with resolution 1920x1080.
I notice we can change `w1920-h1080` to `w1920-h1200` and its link still work.

Could you please have a new `backgrounds_w1920_h1200.json` in case who needs it?

**Comment by dconnolly** [comment]
If you would like different resolutions, you can use the ```cli.js``` script to find the urls of any width/height/size combination you like. ```npm install; ./cli.js --help``` to see other options available.
